USE [Database_ResearchRepository]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Theses] (
    [Id]          INT         NOT NULL,
    [Name]        varchar (300)  NULL,
    [PublicationDate]   DATETIME    NULL,
    [Summary]     varchar(8000)    NULL,
);

INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (1, N'2.0 Social Networks Have an Impact on our Real Lives (2011)', N'2011-09-12 00:00:00',N'Insomnio, ansiedad y dolores musculares, entre las consecuencias para la salud del uso abusivo del teléfono móvil. Pero no solo produce problemas para conciliar el sueño, el teléfono móvil también incrementaría las posibilidades de padecer un cáncer de próstata y de mama.')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (2, N'Representation of Graphs', N'2020-10-12 00:00:00',N'Given a  formulation of a  problem,  a  compact representation is required both  for theoretical purposes  -  measuring the complexity of algo- rithms, and for practical purposes -  data compression. The adjacency lists  method for representing graphs  is compared  to the information theoretic lower bounds, and it is shown to be  optimal in many instances.  For  n-vertex  labeled  planar  graphs  the  adjacency lists  method requires 3nlogn+O(n) bits,  a  linear  algorithm  is  presented  to  obtain  a 3/2n log n+O(n) representation while n log n+O(n) is shown to be the mini- mum.')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (3, N'AGENT-ORIENTED APPROACHES FOR MODEL-BASED SOFTWARE TESTING: A MAPPING STUDY', N'2020-10-12 00:00:00',N'Automated software testing reduces manual work, increases test coverage, and improves error detection. Model-Based Testing (MBT) is a testing approach that automatically executes test cases generated from a model representing the system behavior. The parallelization of MBT process stages, such as model creation and exploration, or test case generation and execution, could improve its scalability to handle complex systems. ')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (4, N'Smart Construction from Head to Toe: A Closed-Loop Lifecycle Management System Based on IoT ', N'2020-10-12 00:00:00',N'The current lifecycle management of construction projects has long been plagued by the dilemma of “lack of information” and “information explosion”. This paper aims to develop a closed-loop lifecycle management system that can enable a consistent stream of information for use and reuse of all stakeholders. The framework integrates the state-of-the-art smart construction, construction automation and internet of things (IoT) technologies to help fragmented practitioners access and manage the information via a standardized interface among various applications throughout the whole lifecycle. Within the closed-loop lifecycle management system for IoT-based smart construction, digital technologies such as 3D laser scanner, drone, building information modelling (BIM), augmented reality (AR), Auto-ID, global positioning system (GPS), wireless sensor network (WSN), robotics, mobile digital devices, and web-based applications are used to collect proactive data from different stages. Further, the data are stored, shared, processed, and utilized in one unified platform for all stakeholders to support better decision-making and interaction throughout a project lifecycle. The framework is a guideline of real-time visualized tracking and operation, real-time environment supervision, real-time feedback and alarm, cloud backup, and data analysis demonstration which enable smart construction from head to toe.')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (5, N'A simple tree search method for playing Ms. Pac-Man', N'2011-09-11 00:00:00',N'Ms. Pac-Man is a challenging game for software agents that has been the focus of a significant amount of research. This paper describes the current state of a tree-search software agent that will be entered into the IEEE CIG 2009 screen-capture based Ms. Pac-Man software agent competition. While game-tree search is a staple technique for many games, this paper is, perhaps surprisingly, the first attempt we know of to apply it to Ms. Pac-Man. The approach we take is to expand a route-tree based on possible moves that the Ms. Pac-Man agent can take to depth 40, and evaluate which path is best using hand-coded heuristics. On a simulator of the game our agent has achieved a high score of 40,000, but only around 15,000 on the original game using a screen-capture interface. Our next steps are focussed on using an improved screen-capture system, and on using evolutionary algorithms to tune the parameters of the agent.')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (6, N'ONLINE JUDGE SUPPORT FOR PROGRAMMING TEACHING', N'2015-09-11 00:00:00',N'Online programming judges are considered useful and sometimes indispensable tools to support competitive programming, professionals recruiting, and programming education. In this last field, the scientific literature on these tools focuses on the learners needs, but neglects the requirements of the professors, even though they are who mainly decide whether or not an educational tool is adopted in the courses they teach. ')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (7, N'Neural Networks and Learning Machines', N'2001-05-12 00:00:00',N'Work on artificial neural networks, commonly referred to as “neural networks,” has been motivated right from its inception by the recognition that the human brain computes in an entirely different way from the conventional digital computer. The brain is a highly complex, nonlinear, and parallel computer (information-processing system). It has the capability to organize its structural constituents, known as neurons, so as to perform certain computations (e.g., pattern recognition, perception, and motor control) many times faster than the fastest digital computer in existence today. Consider,for example, human vision, which is an information-processing task. It is the function of the visual system to provide a representation of the environment around us and, more important, to supply the information we need to interact with the environment. To be specific, the brain routinely accomplishes perceptual recognition tasks (e.g., recognizing a familiar face embedded in an unfamiliar scene) in approximately 100–200 ms, whereas tasks of much lesser complexity take a great deal longer on a powerful computer.')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (8, N'SMART CITIES IN LATIN AMERICA', N'2021-09-12 00:00:00',N'In almost every forum around the world, country leaders are discussing the necessity of creating smart cities. However, even the term ``smart city'' is diffuse nowadays. Some countries want their cities to become smarter and others want to create smart cities from scratch. Several mappings have been developed around the world to locate the smartest cities. We believe that, since Latin American and Caribbean countries are exploring in the creation of smart cities, a proper mapping and plan is necessary to assure that the efforts in creating smart cities are not a waste. Using a literature review and a survey, we try to determine the state of smart cities development and its technical readiness in the Region.')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (9, N'Nanotechnology Big Things from a Tiny World', N'2021-02-10 00:00:00',N'Nanomedicine Nanomedicine, the application of nanotechnology in medicine, enables precise solutions for disease prevention, diagnosis, andtreatment. This includes new imaging tools like improved MRIs; labon-a-chip technologies for rapid testing in a doctor’s office; novelgene sequencing technologies; nanoparticles that can help deliver medication directly to cancer cells, minimizing damage to healthy tissue; and graphene nanoribbons to help repair spinal cord injuries. ')
INSERT INTO [dbo].[Theses] ([Id], [Name], [PublicationDate], [Summary]) VALUES (10, N'Smart Meeting Room Management System Based on Real-Time Occupancy', N'2019-08-11 00:00:00', N'This paper proposes the creation of a smart meeting room through the incorporation of a PIR sensor and an AWS IoT button that allows the booking system to reflect a more precise availability of meeting rooms according to the actual occupancy status. The Internet of Things (IoT) devices are controlled using a Wi-Fi module that allows them to connect to the REST web service and to integrate with the open source Meeting Room Booking System (MRBS). In order to evaluate the system a storyboard evaluation was conducted with 47 participants. All participants filled out the User Experience Questionnaires (UEQ), described the product using three words and expressed their opinion through open comments. Finally, 19 participants took part in a real-life simulation of the smart meeting room and evaluated the system using the UEQ questionnaire. Based on the positive acceptance reflected in the evaluations, results show that the proposed system is considered very attractive and useful by the participants.')



